{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skills-agent.serviceAccountName" . }}
  {{- if .Values.serviceAccount.namespace }}
  namespace: {{ .Values.serviceAccount.namespace }}
  {{- end }}
  labels:
    {{- include "skills-agent.labels" . | nindent 4 }}
  {{- if and .Values.storeResults.enabled .Values.storeResults.iamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.storeResults.iamRoleArn }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
